replicaCount: 2
image: qlikea/engine:12.150.0
service:
  name: qix
  externalPort: 9076
  internalPort: 9076
  promName: prometheus
  prometheusPort: 9090
  serviceType: ClusterIP
global:
  imagePullPolicy: IfNotPresent
