version: "3.1"

services:
  mira:
    image: qlikcore/mira${TAG} # If TAG is not set docker image with tag 'latest' will be used.
    ports:
      - "9100:9100"
    environment:
     - MIRA_MODE=local
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  engine1:
    image: qlikcore/engine:12.248.0
    command: -S AcceptEULA=${ACCEPT_EULA}
    ports:
      - "9176:9076"
    labels:
      qix-engine: ""

  engine2:
    image: qlikcore/engine:12.248.0
    command: -S AcceptEULA=${ACCEPT_EULA}
    ports:
      - "9276:9076"
    labels:
      qix-engine: ""
