version: "3.1"

services:
  mira:
    image: qlikea/mira${TAG} # If TAG is not set docker image with tag 'latest' will be used.
    ports:
      - "9100:9100"
    environment:
     - MIRA_MODE=local
     - MIRA_DISCOVERY_LABEL=qix-engine-local
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  engine1:
    image: qlikea/engine:12.48.0
    ports:
      - "9176:9076"
    labels:
      qix-engine-local:
      qix-engine-api-port: "9076"
      qix-engine-metrics-port: "9090"

  engine2:
    image: qlikea/engine:12.48.0
    ports:
      - "9276:9076"
    labels:
      qix-engine-local:
      qix-engine-metrics-port: "9090"
