apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: engine
  labels:
    app: engine
  annotations:
    prometheus.io/scrape: "true"
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: engine
        service: engine
        qix-engine: ""
    spec:
      containers:
      - name: engine
        image: "qlikcore/engine:12.612.0"
        imagePullPolicy: IfNotPresent
        args: ["-S", "AcceptEULA=no"]
        ports:
        - containerPort: 9076
        - containerPort: 9090
