version: "3.1"

services:
  mira:
    image: qlikea/mira:latest
    ports:
      - "9100:9100"
    command: --mode swarm
    environment:
     - DISCOVERY=qix-engine, qix-engine-dev
    deploy:
      mode: global
      placement:
        constraints: [node.role == manager]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  engine1:
    image: qlikea/engine:12.42.0
    ports:
      - "9176:9076"
    labels:
      mira-discovery-id: qix-engine
    deploy:
      replicas: 2
      placement:
        constraints: [node.role == manager]

  engine2:
    image: qlikea/engine:12.42.0
    ports:
      - "9276:9076"
    labels:
      mira-discovery-id: qix-engine-dev
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
