apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: engine-deployment
spec:
  replicas: 2
  template:
    metadata:
      labels:
        service: engine
        com.qlik.mira.id: qix-engine
    spec:
      containers:
      - name: engine
        image: qlikea/engine:12.38.0
        ports:
        - containerPort: 9076
      restartPolicy: Always
      imagePullSecrets:
        - name: dockerhub
