apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mira
  labels:
    app: mira
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mira
    spec:
      containers:
      - name: mira
        image: "qlikcore/mira:0.4.0"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9100
        env:
        - name: MIRA_MODE
          value: kubernetes
      - name: kubectl
        image: lachlanevenson/k8s-kubectl:v1.9.10
        args: [ "proxy", "-p", "8001" ]
        imagePullPolicy: IfNotPresent
