info:
  title: A Qlik Associative Engine discovery service
  version: 0.1.2
  description: >-
    REST API for discovering Qlik Associative Engines running in Docker containers.
host: 'localhost:9100'
schemes:
  - http
basePath: /v1
x-qlik-visibility: private
x-qlik-stability: experimental
swagger: '2.0'
paths:
  /health:
    get:
      description: Returns health status of the Mira service
      produces:
        - application/json; charset=utf-8
      responses:
        '200':
          description: successful operation
          schema:
            type: object
  /metrics:
    get:
      description: Returns metrics of the Mira service
      produces:
        - application/json; charset=utf-8
        - text/plain; charset=utf-8
      responses:
        '200':
          description: successful operation
          schema:
            type: array
            description: Default prometheus client metrics
  /engines:
    get:
      description: Lists available Qlik Associative Engines.
      produces:
        - application/json; charset=utf-8
      parameters:
        - name: format
          in: query
          description: If result should be in full or condensed format.
          required: false
          type: string
          default: full
      responses:
        '200':
          description: successful operation
          schema:
            type: array
            items:
              $ref: '#/definitions/containerInfo'
        '503':
          description: Service Unavailable
definitions:
  engineInfo:
    type: object
    required:
      - ip
      - port
      - metricsPort
      - status
    properties:
      ip:
        description: IP address to use when connecting to the Qlik Associative Engine.
        type: string
      port:
        description: Port to use when communicating with the Qlik Associative Engine API.
        type: number
      metricsPort:
        description: Port to use when retrieving the Qlik Associative Engine metrics.
        type: number
      status:
        $ref: '#/definitions/containerStatus'
      health:
        description: Last health endpoint response of the Qlik Associative Engine.
        type: object
      metrics:
        description: Last metrics endpoint response of the Qlik Associative Engine.
  containerInfo:
    type: object
    required:
      - engine
    properties:
      engine:
        $ref: '#/definitions/engineInfo'
      local:
        type: object
        description: >-
          Container information in verbatim format as returned by the Docker
          Engine Remote API.
      swarm:
        type: object
        description: >-
          Task information in verbatim format as returned by the Docker Engine
          Remote API.
      kubernetes:
        type: object
        description: Pod information in verbatim format as returned by the Kubernetes API.
  containerStatus:
    type: string
    description: Status of the Qlik Associative Engine.
    enum:
      - OK
      - UNHEALTHY
      - NO_METRICS
responses: {}
parameters: {}
securityDefinitions: {}
tags: []
