info:
  title: A QIX Engine discovery service for Qlik Elastic
  version: 0.0.2
  description: >-
    REST API for discovering QIX Engines running in Docker containers. Different
    modes exist, local, swarm and kubernetes mode.
host: 'localhost:9100'
schemes:
  - http
basePath: /v1
x-qlik-visibility: private
x-qlik-stability: experimental
swagger: '2.0'
paths:
  /health:
    get:
      description: Returns health status of the Mira service
      responses:
        '200':
          description: OK
  /engines:
    get:
      description: Lists available QIX Engines.
      produces:
        - application/json
      responses:
        '200':
          description: successful operation
          schema:
            type: array
            items:
              $ref: '#/definitions/containerInfo'
definitions:
  engineInfo:
    type: object
    properties:
      ip:
        description: IP address to use when connecting to the QIX Engine.
        type: string
      port:
        description: Port to use when communicating with the QIX Engine API.
        type: number
      metricsPort:
        description: Port to use when retrieving the QIX Engine metrics.
        type: number
      status:
        $ref: '#/definitions/containerStatus'
      health:
        description: Last health endpoint response of the QIX Engine.
        type: object
      metrics:
        description: Last metrics endpoint response of the QIX Engine.
  containerInfo:
    type: object
    required:
      - engine
    properties:
      engine:
        $ref: '#/definitions/engineInfo'
      local:
        type: object
        description: >-
          Container information in verbatim format as returned by the Docker
          Engine Remote API.
      swarm:
        type: object
        description: >-
          Task information in verbatim format as returned by the Docker Engine
          Remote API.
      kubernetes:
        type: object
        description: Pod information in verbatim format as returned by the Kubernetes API.
  containerStatus:
    type: string
    description: Status of the QIX Engine.
    enum:
      - OK
      - UNHEALTHY
      - NO_METRICS
responses: {}
parameters: {}
securityDefinitions: {}
tags: []
