apiVersion: v1
kind: ServiceAccount
metadata:
  name: mira
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: mira
rules:
  - apiGroups:
      - ""
      - extensions
      - apps
    resources:
      - pods
      - replicasets
      - deployments
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: mira
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: mira
subjects:
  - kind: ServiceAccount
    name: mira
