miraMode: kubernetes
replicaCount: 1
image:
  repository: qlikcore/mira
  tag: 0.1.0
  pullPolicy: IfNotPresent
sideCartContainerName: kubectl
sideCartContainerArgs: "[ \"proxy\", \"-p\", \"8001\" ]"
sideCartContainerImage: lachlanevenson/k8s-kubectl:v1.9.10
service:
  name: mira
  externalPort: 9100
  internalPort: 9100
  type: ClusterIP
serviceAccount: default
useRollbar: false
