miraMode: kubernetes
replicaCount: 1
image:
  repository: qlikcore/mira
  tag: 2.0.0
  pullPolicy: IfNotPresent
service:
  name: mira
  externalPort: 9100
  internalPort: 9100
  type: ClusterIP
serviceAccount: default
useRollbar: false
